### ISSUE TITLE
Create a new git release for Homebrew

### ISSUE THREAD

**Issue by rgardner** [kennethreitz/autoenv#106] opened 2016-05-07 02:22 UTC
Homebrew uses the `0.1.0` release of `autoenv` that was released on February 15th, 2012. I just ran into a bug with whitespace handling that is broken in `0.1.0` but has been fixed since then. Can you please do another release of autoenv? The `LICENSE` file also says Copyright 2012, which you may want to bump.

**Comment by harrislapiroff** [comment] 2016-06-25 23:37
+1 to this! Would be v. appreciative. 💞

**Comment by harrislapiroff** [comment] 2016-06-25 23:38
This is probably a dupe of #82, though, eh?

**Comment by dasJ** [comment] 2016-08-01 07:40
Duplicate of #61

**Closed by dasJ** 2016-08-01 07:40 UTC
