### ISSUE TITLE
Updating Homebrew formula

### ISSUE THREAD

**Issue by pikeas** [kennethreitz/autoenv#82] opened 2015-05-15 09:38 UTC
I opened a PR at https://github.com/Homebrew/homebrew/pull/39777/files#r30395826, but they want a "tagged, stable release". Could you add a tag for version 1.0.0?

**Comment by pikeas** [comment] 2015-08-10 02:25
Bump, would really like to get this into Homebrew (https://github.com/Homebrew/homebrew/pull/39777).

**Comment by jayqi** [comment] 2016-02-25 22:47
Bumping as this is still an issue. 

For those who find this thread and still would like to install using Homebrew, the suggested workaround in the [Homebrew PR thread](https://github.com/Homebrew/homebrew/pull/39777) to install the latest version is: `brew install --HEAD autoenv`

**Comment by kennethreitz** [comment] 2016-02-25 23:47
I will get to this soon!

**Comment by kennethreitz** [comment] 2016-02-25 23:48
Feel free to comment here if there's no progress within the next few days (I'll get re-notified).

**Comment by pikeas** [comment] 2016-03-01 07:01
Bump!

**Comment by kennethreitz** [comment] 2016-03-01 21:40
Damnit! :)

**Comment by bartiaco** [comment] 2016-03-09 19:00
Double bump. <3

**Comment by harrislapiroff** [comment] 2016-06-25 23:38
Bump bump. 😇

**Comment by dasJ** [comment] 2016-08-01 07:41
Duplicate of #61

**Closed by dasJ** 2016-08-01 07:41 UTC
